export const nameMapping = {
    cardbanks: {
        aus: [
            "au small finance bank",
            "aus",
            "au small finance bank limited",
            "au small",
            "au small finance",
            "au",
            "aublr",
        ],
        axis: ["axis bank", "axis", "utibr"],
        axisc: ["axisc", "axis corporate", "utibc"],
        bdnc: ["bandhan bank", "bandhan", "bdnc", "bandhan corporate", "bdblc"],
        bdnr: ["bdnr", "bandhan retail", "bdblr"],
        bobc: ["bobc", "bank of baroda", "barbc"],
        bobr: ["bobr", "barbr"],
        boi: ["boi", "bank of india", "bkidr", "bkidc"],
        bom: ["bom", "bank of maharashtra", "mahbr"],
        canara: ["canara", "canara bank", "cnrbr"],
        cbi: ["central bank of india", "cbi", "cbinr"],
        csb: [
            "csb bank",
            "csb",
            "catholic syrian bank limited",
            "catholic syrian bank",
            "csbkr",
        ],
        cub: ["city union bank", "cub", "ciubr", "ciubc"],
        dbs: ["dbs", "dbs bank", "digibank", "dbssr"],
        deutsche: ["deutsche", "deutsche bank", "deutr"],
        dhanlakshmi: ["dhanlakshmi", "dhanlakshmi bank", "dlxbr", "dlxbc"],
        equitas: [
            "equitas small finance bank",
            "equitas",
            "equitas small finance",
            "equitas bank",
            "esfbr",
        ],
        federal: ["federal bank", "federal", "fdrlr"],
        hdfc: ["hdfc", "hdfc bank", "hdfcr", "hdfcc", "hdfc bank limited"],
        icici: ["icici", "icici bank", "icicr", "icicc"],
        idfc: ["idfc", "idfc bank", "idfc first bank", "idfbr"],
        indian: ["indian", "indian bank", "idibr"],
        indusind: ["indusind", "indusind bank", "indbr"],
        iob: [
            "iob",
            "iob bank",
            "indian overseas bank",
            "indian overseas bank",
            "iobar",
        ],
        iobc: [
            "iobc",
            "iob corporate",
            "indian overseas corporate",
            "indian overseas bank corporate",
            "iobac",
        ],
        jkb: [
            "jkb",
            "jammu & kashmir bank",
            "jammu and kashmir bank",
            "j&k bank",
            "jakar",
        ],
        karnatka: [
            "karnataka",
            "karnataka bank",
            "karnatka",
            "karnatka bank",
            "karbr",
        ],
        karur: [
            "karur",
            "karur bank",
            "karur vysya bank",
            "karur vysya",
            "kvblr",
        ],
        kotak: ["kotak", "kotak bank", "kkbkr"],
        lvbc: ["lvbc", "lvb corporate", "lavbc"],
        lvbr: ["lvbr", "lvb retail", "lavbr"],
        pnbc: [
            "pnbc",
            "punjab national bank corporate",
            "pnb",
            "punjab national bank",
            "punbc",
        ],
        pnbr: ["pnbr", "punjab national bank retail", "punbr"],
        rbl: ["rbl", "ratnakar bank", "rbl bank", "ratnr"],
        rblc: ["rbl corporate", "rblc", "ratnc"],
        saraswat: ["saraswat", "saraswat bank", "srcbr"],
        sbi: ["sbi", "state bank of india", "sbinr"],
        sbic: [
            "sbic",
            "sbi corporate",
            "state bank of india corporate",
            "sbinc",
        ],
        scb: ["scb", "standard chartered", "standard chartered bank", "scblr"],
        shivalik: ["shivalik", "shivalik bank", "smcbr"],
        sib: ["sib", "south indian bank", "siblr"],
        sur: ["sur", "sur bank"],
        tamcop: ["tamcop", "tamcop bank"],
        tammerc: ["tammerc", "tammerc bank"],
        uco: ["uco", "uco bank", "united commercial bank", "ucbar", "ucbac"],
        union: ["union", "union bank", "ubinr", "ubinc"],
        utk: [
            "utk",
            "utk bank",
            "utkarsh small finance bank",
            "utkarsh small finance",
            "utksr",
        ],
        yes: ["yes", "yes bank", "yesbc", "yesbr"],
    },
    cardschemes: {
        amex: ["amex"],
        diners: ["diners"],
        discover: ["discover"],
        jcb: ["jcb"],
        maestro: ["maestro"],
        mastercard: ["mastercard"],
        rupay: ["rupay"],
        visa: ["visa"],
    },
    paylater: {
        epaylater: ["epaylater"],
        freecharge: ["freecharge", "freechargepaylater"],
        hdfc: ["hdfc", "hdfcpaylater"],
        kotak: ["kotak", "kotakpaylater"],
        lazypay: ["lazypay"],
        olapostpaid: ["olapostpaid"],
        simpl: ["simpl"],
        zestmoneypaylater: ["zestmoney", "zestmoneypaylater"],
    },
    upi: {
        bhim: ["bhim", "upi"],
        gpay: ["gpay", "googlepay"],
        paytm: ["paytm"],
        phonepe: ["phonepe"],
        whatsapp: ["whatsapp"],
        credpay: ["cred", "credpay"],
    },
    wallet: {
        airtel: ["airtel", "airtelmoney", "airpr"],
        amazon: ["amazon", "amazonpay"],
        freecharge: ["freecharge"],
        jio: ["jio", "jiomoney", "jiopr"],
        mobikwik: ["mobikwik"],
        ola: ["ola"],
        paytm: ["paytm"],
        phonepe: ["phonepe"],
        paypal: ["paypal"],
    },
    cardless: {
        flexipay: ["flexipay"],
    }
};
