export const nameMapping = {
    cardbanks: {
        aus: [
            "au small finance bank",
            "aus",
            "au small finance bank limited",
            "au small",
            "au small finance",
            "au"
        ],
        axis: ["axis bank", "axis"],
        axisc: ["axisc", "axis corporate"],
        bdnc: ["bandhan bank", "bandhan", "bdnc", "bandhan corporate"],
        bdnr: ["bdnr", "bandhan retail"],
        bobc: ["bobc", "bank of baroda"],
        bobr: ["bobr"],
        boi: ["boi", "bank of india"],
        bom: ["bom", "bank of maharashtra"],
        canara: ["canara", "canara bank"],
        cbi: ["central bank of india", "cbi"],
        csb: [
            "csb bank",
            "csb",
            "catholic syrian bank limited",
            "catholic syrian bank",
        ],
        cub: ["city union bank", "cub"],
        dbs: ["dbs", "dbs bank", "digibank"],
        deutsche: ["deutsche", "deutsche bank"],
        dhanlakshmi: ["dhanlakshmi", "dhanlakshmi bank"],
        equitas: [
            "equitas small finance bank",
            "equitas",
            "equitas small finance",
            "equitas bank",
        ],
        federal: ["federal bank", "federal"],
        hdfc: ["hdfc", "hdfc bank"],
        icici: ["icici", "icici bank"],
        idfc: ["idfc", "idfc bank", "idfc first bank"],
        indian: ["indian", "indian bank"],
        indusind: ["indusind", "indusind bank"],
        iob: [
            "iob",
            "iob bank",
            "indian overseas bank",
            "indian overseas bank",
        ],
        iobc: [
            "iobc",
            "iob corporate",
            "indian overseas corporate",
            "indian overseas bank corporate",
        ],
        jkb: [
            "jkb",
            "jammu & kashmir bank",
            "jammu and kashmir bank",
            "j&k bank",
        ],
        karnataka: ["karnataka", "karnataka bank"],
        karur: ["karur", "karur bank", "karur vysya bank", "karur vysya"],
        kotak: ["kotak", "kotak bank"],
        lvbc: ["lvbc", "lvb corporate"],
        lvbr: ["lvbr", "lvb retail"],
        pnbc: [
            "pnbc",
            "punjab national bank corporate",
            "pnb",
            "punjab national bank",
        ],
        pnbr: ["pnbr", "punjab national bank retail"],
        rbl: ["rbl", "ratnakar bank", "rbl bank"],
        rblc: ["rbl corporate", "rblc"],
        saraswat: ["saraswat", "saraswat bank"],
        sbi: ["sbi", "state bank of india"],
        sbic: ["sbic", "sbi corporate", "state bank of india corporate"],
        scb: ["scb", "standard chartered", "standard chartered bank"],
        shivalik: ["shivalik", "shivalik bank"],
        sib: ["sib", "south indian bank"],
        sur: ["sur", "sur bank"],
        tamcop: ["tamcop", "tamcop bank"],
        tammerc: ["tammerc", "tammerc bank"],
        uco: ["uco", "uco bank", "united commercial bank"],
        union: ["union", "union bank"],
        utk: [
            "utk",
            "utk bank",
            "utkarsh small finance bank",
            "utkarsh small finance",
        ],
        yes: ["yes", "yes bank"],
    },
    cardschemes: {
        amex: ['amex'],
        diners: ['diners'],
        discover: ['discover'],
        jcb: ['jcb'],
        maestro: ['maestro'],
        mastercard: ['mastercard'],
        paypal: ['paypal'],
        rupay: ['rupay'],
        visa: ['visa'],
    },
    paylater: {
        epaylater: ['epaylater'],
        freecharge: ['freecharge', 'freechargepaylater'],
        hdfc: ['hdfc', 'hdfcpaylater'],
        kotak: ['kotak', 'kotakpaylater'],
        lazypay: ['lazypay'],
        olapostpaid: ['olapostpaid'],
        simpl: ['simpl'],
        zestmoneypaylater: ['zestmoney', 'zestmoneypaylater'], 
    },
    upi: {
        bhim: ['bhim'],
        gpay: ['gpay', 'googlepay'],
        paytm: ['paytm'],
        phonepe: ['phonepe'],
    },
    wallet: {
        airtel: ['airtel', 'airtelmoney'],
        amazon: ['amazon', 'amazonpay'],
        freecharge: ['freecharge'],
        jio: ['jio', 'jiomoney'],
        mobikwik: ['mobikwik'],
        ola: ['ola'],
        paytm: ['paytm'],
        phonepe: ['phonepe'],
    },
};
