export const nameMapping = {
    cardbanks: {
        amex: ["amexccemi"],
        aus: [
            "au small finance bank",
            "aus",
            "au small finance bank limited",
            "au small",
            "au small finance",
            "au",
            "aublr",
            "ausmallccemi",
        ],
        axis: ["axis bank", "axis", "utibr"],
        axisc: ["axisc", "axis corporate", "utibc"],
        bdnc: [
            "bandhan bank",
            "bandhan",
            "bdnc",
            "bandhan corporate",
            "bdblc",
            "bandhan bank - corporate",
        ],
        bdnr: [
            "bdnr",
            "bandhan retail",
            "bdblr",
            "bandhan bank - retail banking",
        ],
        bobc: [
            "bobc",
            "bank of baroda",
            "barbc",
            "bank of baroda - corporate",
            "bob",
        ],
        bobr: ["bobr", "barbr", "bank of baroda - retail banking"],
        boi: ["boi", "bank of india", "bkidr", "bkidc", "boic"],
        bom: ["bom", "bank of maharashtra", "mahbr"],
        canara: ["canara", "canara bank", "cnrbr"],
        cbi: ["central bank of india", "cbi", "cbinr"],
        csb: [
            "csb bank",
            "csb",
            "catholic syrian bank limited",
            "catholic syrian bank",
            "csbkr",
        ],
        cub: ["city union bank", "cub", "ciubr", "ciubc", "cubc"],
        dbs: ["dbs", "dbs bank", "digibank", "dbssr"],
        deutsche: ["deutsche", "deutsche bank", "deutr"],
        dhanlakshmi: [
            "dhanlakshmi",
            "dhanlakshmi bank",
            "dlxbr",
            "dlxbc",
            "dhanc",
        ],
        equitas: [
            "equitas small finance bank",
            "equitas",
            "equitas small finance",
            "equitas bank",
            "esfbr",
        ],
        federal: ["federal bank", "federal", "fdrlr"],
        hdfc: ["hdfc", "hdfc bank", "hdfcr", "hdfcc", "hdfc bank limited"],
        icici: ["icici", "icici bank", "icicir", "icicic"],
        idfc: ["idfc", "idfc bank", "idfc first bank", "idfbr"],
        indian: ["indian", "indian bank", "idibr"],
        indusind: ["indusind", "indusind bank", "indbr"],
        iob: [
            "iob",
            "iob bank",
            "indian overseas bank",
            "indian overseas bank",
            "iobar",
        ],
        iobc: [
            "iobc",
            "iob corporate",
            "indian overseas corporate",
            "indian overseas bank corporate",
            "iobac",
        ],
        jkb: [
            "jkb",
            "jammu & kashmir bank",
            "jammu and kashmir bank",
            "j&k bank",
            "jakar",
        ],
        karnatka: [
            "karnataka",
            "karnataka bank",
            "karnatka",
            "karnatka bank",
            "karbr",
        ],
        karur: [
            "karur",
            "karur bank",
            "karur vysya bank",
            "karur vysya",
            "kvblr",
        ],
        kotak: ["kotak", "kotak bank", "kkbkr", "kotak mahindra bank"],
        lvbc: ["lvbc", "lvb corporate", "lavbc"],
        lvbr: ["lvbr", "lvb retail", "lavbr"],
        pnbc: [
            "pnbc",
            "punjab national bank corporate",
            "pnb",
            "punjab national bank",
            "punbc",
            "punjab national bank - corporate",
        ],
        pnbr: [
            "pnbr",
            "punjab national bank retail",
            "punbr",
            "punjab national bank - retail banking",
        ],
        rbl: ["rbl", "ratnakar bank", "rbl bank", "ratnr"],
        rblc: ["rbl corporate", "rblc", "ratnc", "rtc"],
        saraswat: ["saraswat", "saraswat bank", "srcbr"],
        sbi: ["sbi", "state bank of india", "sbinr"],
        sbic: [
            "sbic",
            "sbi corporate",
            "state bank of india corporate",
            "sbinc",
        ],
        scb: [
            "scb",
            "standard chartered",
            "standard chartered bank",
            "scblr",
            "sc",
        ],
        shivalik: ["shivalik", "shivalik bank", "smcbr"],
        sib: ["sib", "south indian bank", "siblr"],
        sur: ["sur", "sur bank", "surat peoples cooperative bank"],
        tamcop: ["tamcop", "tamcop bank"],
        tammerc: ["tammerc", "tammerc bank"],
        uco: [
            "uco",
            "uco bank",
            "united commercial bank",
            "ucbar",
            "ucbac",
            "ucc",
        ],
        union: ["union", "union bank", "ubinr", "ubinc", "ubic", "union bank of india", "ubi"],
        utk: [
            "utk",
            "utk bank",
            "utkarsh small finance bank",
            "utkarsh small finance",
            "utksr",
        ],
        yes: ["yes", "yes bank", "yesbc", "yesbr", "yesc"],
        allahabad: ["allahabad bank", "allahabad"],
        apg: ["andhra pragathi grameena", "apg"],
        bbk: ["bank of bahrain and kuwait", "bbk"],
        bcb: ["bassien catholic coop", "bcb"],
        bclc: ["barclays", "barclays corporate", "bclc"],
        cpb: ["capital small finance", "cpb"],
        dcb: ["dcb", "dcbc", "dcbp", "dcb bank"],
        esaf: ["esaf", "esaf small finance", "esf"],
        fnc: ["fincare", "fnc"],
        gsb: ["gsb", "gujarat state cooperative bank"],
        hsb: ["hsb", "hsbc", "hsbc bank"],
        jsb: ["jsb", "janata sahakari bank"],
        kjb: ["kjb", "kalyan janata sahakari bank"],
        klb: ["klb", "kalapur commercial cooperative bank"],
        kvg: ["kvg", "karnataka vikas grameena bank"],
        mgb: ["mgb", "maharashtra gramin bank"],
        msb: ["msb", "mehsana urban cooperative bank"],
        neb: ["neb", "north east small finance bank"],
        nkb: ["nkb", "nkgsb", "nkgsb cooperative bank"],
        nut: ["nut", "nuthan nagarik sahakari bank"],
        pkb: ["pkb", "karnataka gramin bank"],
        som: ["som", "sbm bank"],
        srb: ["srb", "suryodaya small finance bank"],
        sut: ["sut", "sutex", "sutex cooperative bank"],
        tbb: ["tbb", "thane bharat sahakari bank", "thane bharat"],
        tjb: ["tjsb", "tjb", "tjsb sahakari bank"],
        vijaya: ["vijaya", "vijaya bank"],
        vrb: ["vrb", "varachha", "varachha cooperative bank"],
        zob: ["zob", "zoroastrian cooperative bank"],
        airtel: ["airtelnb"],
        paytm: ["paytmnb"],
        idbi: ["idbi", "idbi bank", "idbicorpnb"],
        pnsb: ["pnsb", "punjab and sind bank"],
        svcb: ["svcb", "shamrao vittal cooperative bank", "svbc"],
        cob: ["cob", "cosmos", "cosmos bank"],
        jnb: ["jnb", "jana small finance bank"],
        usfb: ["usfb", "ujjivan small finance bank"],
        citi: ["citi", "citi bank"],
    },
    cardschemes: {
        amex: ["amex"],
        diners: ["diners"],
        discover: ["discover"],
        jcb: ["jcb"],
        maestro: ["maestro"],
        mastercard: ["mastercard"],
        rupay: ["rupay"],
        visa: ["visa"],
    },
    paylater: {
        epaylater: ["epaylater"],
        freecharge: ["freecharge", "freechargepaylater"],
        hdfc: ["hdfc", "hdfcpaylater"],
        kotak: ["kotak", "kotakpaylater"],
        lazypay: ["lazypay"],
        olapostpaid: ["olapostpaid", "ola"],
        simpl: ["simpl"],
        zestmoneypaylater: ["zestmoney", "zestmoneypaylater"],
        mobikwik: ["mobikwikpaylater", "mobikwik"],
        ringpaylater: ["ringpay", "ringpaylater"],
    },
    upi: {
        bhim: ["bhim", "upi"],
        gpay: ["gpay", "googlepay"],
        paytm: ["paytm"],
        phonepe: ["phonepe"],
        whatsapp: ["whatsapp"],
        credpay: ["cred", "credpay"],
    },
    wallet: {
        airtel: [
            "airtel",
            "airtelmoney",
            "airpr",
            "airtel money",
            "airtel payments bank",
        ],
        amazon: ["amazon", "amazonpay"],
        freecharge: ["freecharge"],
        jio: [
            "jio",
            "jiomoney",
            "jiopr",
            "reliance jio money",
            "jio payments bank",
            "jpb",
        ],
        mobikwik: ["mobikwik"],
        ola: ["ola"],
        paytm: ["paytm"],
        phonepe: ["phonepe"],
        paypal: ["paypal"],
        payzapp: ["payzapp"],
    },
    cardless: {
        flexipay: ["flexipay"],
        snapmint: ["snapmint"],
        cashe: ["cashe"],
        kreditbee: ["kreditbee"],
    },
};
